/**********************************************************************/
/* File:                                                              */
/* Author:                                                            */
/* This codes is generated by CFortranTranslator                      */
/* CFortranTranslator is published under GPL license                  */
/* refer to https://github.com/CalvinNeo/CFortranTranslator/ for more */
/**********************************************************************/
#include "../for90std/for90std.h" 
#define USE_FORARRAY 
#include "ma.h"
int main()
{
	car car1;
	car * car2 = nullptr;
	car1.speed = 1.0;
	car2 =&(car1);
	xx(INOUT((*(car2)).speed));
	
	
	return 0;
}
