/**********************************************************************/
/* File:                                                              */
/* Author:                                                            */
/* This codes is generated by CFortranTranslator                      */
/* CFortranTranslator is published under GPL license                  */
/* refer to https://github.com/CalvinNeo/CFortranTranslator/ for more */
/**********************************************************************/
#include "../for90std/for90std.h" 
#define USE_FORARRAY 
int main()
{
	int i = 0;
	int j = 0;
	int k = 0;
	
	for(i = 1; i <= 3; i += 1){
		for(j = 1; j <= 3; j += 1){
			for(k = 1; k <= 3; k += 1){
				forprintfree(SS("(i, j, k): "), i, j, k);
				
				if (k == 2) {
					goto jloop;
					
				}
				
				
			}
			kloop:nop();
			
		}
		jloop:nop();
		
	}
	iloop:nop();
	
	while(true){
		break;
		
	}
	banana:nop();
	
	
	
	return 0;
}
