/**********************************************************************/
/* File:                                                              */
/* Author:                                                            */
/* This codes is generated by CFortranTranslator                      */
/* CFortranTranslator is published under GPL license                  */
/* refer to https://github.com/CalvinNeo/CFortranTranslator/ for more */
/**********************************************************************/
#include "../../for90std/for90std.h" 
#include <cstdio>
#define USE_FORARRAY 
int main()
{
  int i = 0;
  int j=0;
	string str = "                    ";
        str = SS("111 222");
        IOFormat fmt = IOFormat{"%d%d"};
        forreadfree(str, &i,&j);
         // forreadfree(stdin, &i,&j);
        forwritefree(stdout, i,j);
	return 0;
}
