/**********************************************************************/
/* File:                                                              */
/* Author:                                                            */
/* This codes is generated by CFortranTranslator                      */
/* CFortranTranslator is published under GPL license                  */
/* refer to https://github.com/CalvinNeo/CFortranTranslator/ for more */
/**********************************************************************/
#include "../for90std/for90std.h" 
#define USE_FORARRAY 
int main()
{
	int ios = 0;
	foropenfile(1, ios, None, SS("exercise_open.tmp"), SS("unknown"), SS("direct"), None, 4, None, SS("rewind"), SS("readwrite"), None, None);
	forwritefree(6, get_file(6), ( ios == 0 ));
	
	
	return 0;
}
