/**********************************************************************/
/* File:                                                              */
/* Author:                                                            */
/* This codes is generated by CFortranTranslator                      */
/* CFortranTranslator is published under GPL license                  */
/* refer to https://github.com/CalvinNeo/CFortranTranslator/ for more */
/**********************************************************************/
#include "../for90std/for90std.h" 
#define USE_FORARRAY 
int main()
{
	string a = "          ";
	string add = "                    ";
	string b = "          ";
	string c = "                    ";
	double char = 0.0;
	string d = "                    ";
	string e = "                    ";
	string first = "      ";
	int ichar = 0;
	int index = 0;
	int key = 0;
	int num = 0;
	string second = "          ";
	string sstring = "                    ";
	double trim = 0.0;
	/*!声明字符串的方法*/
	/*!Fortran 90 添加*/
	/*!Fortran 77*/
	/*!Fortran 77*/
	/*!Fortran 77*/
	
	/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/
	
	
	a = SS("Hello");
	/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/
	/*!字符串赋值*/
	/*!Fortran 90 可用双引号来封装字符串*/
	b = SS("Hello");
	/*!Fortran 77 只能用单引号来封装字符串*/
	c = SS("That's right.");
	/*!用双引号封装字符串时，可以在字符串中任意使用单引号*/
	
	
	
	sstring = SS("Good morning.");
	/*!d='That''s right.' !用单引号封转字符串时，输出单引号时要连续用两个单引号*/
	/*!e="That's ""right""."!用双引号来封装时，输出双引号也要连续使用两个双引号*/
	/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/
	forwritefree(stdout, sstring);
	sstring(INOUT(6)) = SS("evening.");
	/*!重新设置从第6个字符之后的字符串*/
	forwritefree(stdout, sstring); // 该函数第二个参数要对forstring类型进行特殊判断或者另外加个重载
	assign_forslice(sstring, SS("Go"), {{1, 2}}); //在gen_callable.cpp 没有实现
	/*!字符串最前面两个字符变为”Go“*/
	assign_forslice(sstring, SS("!"), {{13, 13}});
	/*!字符串的第13个字符变为“！”*/
	first = SS("Happy ");
	second = SS("Birthday");
	add = first + second;
	/*!经过两个连续的除号可以连接两个字符串*/
	forwritefree(stdout, add);
	
	
	to_string(num);
	/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/
	/*以下函数均未进行特殊定义，其中len()函数必须实现*/
	/*!一些常用函数*/
	/*!返回计算机所使用的字符表上，数值num所代表的字符*/
	ichar(INOUT(char)); // 
	/*!返回所输入的char字符在计算机所使用的字符表中所代表的编号，返回值是整数类型*/
	
	
	// index(INOUT(sstring), INOUT(key));
	/*!len(sstring) !返回输入字符串的声明长度，返回值是整数类型*/
	/*!len_trim(sstring) !返回字符串去除尾端空格后的实际内容长度*/
	/*!所输入的sstring可key都是字符串。这个函数会返回key这个“子字符串”在”母字符串“sstring中第一次出现的位置*/
	trim(INOUT(sstring));
	/*!返回把sstring字符串尾端多余空格清除后的字符串*/
	
	
	return 0;
}
