/**********************************************************************/
/* File:                                                              */
/* Author:                                                            */
/* This codes is generated by CFortranTranslator                      */
/* CFortranTranslator is published under GPL license                  */
/* refer to https://github.com/CalvinNeo/CFortranTranslator/ for more */
/**********************************************************************/
#include "../for90std/for90std.h" 
#define USE_FORARRAY 
#include "adios.h"
#include "adios.h"
void pvmdum();
void pvmfbcast();
void pvmfexit();
void pvmfgsize();
void pvmfinitsend();
void pvmfjoingroup();
void pvmflvgroup();
void pvmfmytid();
void pvmfpack();
void pvmfrecv();
void pvmfunpack();
void pvmdum()
{
	forwritefree(stdout, SS("            ******* Error ******** "));
#ifndef PVM
	/*c*/
	/*c PURPOSE:  dummy library of pvm calls. To use pvm, recompile with*/
	/*c           the entire source with pvm conditional compile flag on*/
	/*c           and link with your local pvm library.*/
	/*c*/
	/*! entry pvmfinitsend*/
	/*! entry pvmfpack*/
	/*! entry pvmfbcast*/
	/*! entry pvmfrecv*/
	/*! entry pvmfunpack*/
	/*! entry pvmfgsize*/
	/*! entry pvmfjoingroup*/
	/*! entry pvmfmytid*/
	/*! entry pvmflvgroup*/
	/*! entry pvmfexit*/
	forwritefree(stdout, SS("DYNA3D is not currently complied/linked with PVM library. "));
	forwritefree(stdout, SS("          "));
	forwritefree(stdout, SS("To use the PVM link option to ATB and MADYMO,"));
	forwritefree(stdout, SS("uncomment the PVM options in the makefile dyna3d.mk"));
	forwritefree(stdout, SS("and remake the executable. "));
	forwritefree(stdout, SS("          "));
	forwritefree(stdout, SS("            ******* Error ******** "));
	adios(INOUT(3));
	
	nop();
#endif
	
	return ;
}

void pvmfinitsend()
{
	forwritefree(stdout, SS("            ******* Error ******** "));
	forwritefree(stdout, SS("DYNA3D is not currently complied/linked with PVM library. "));
	forwritefree(stdout, SS("          "));
	forwritefree(stdout, SS("To use the PVM link option to ATB and MADYMO,"));
	forwritefree(stdout, SS("uncomment the PVM options in the makefile dyna3d.mk"));
	forwritefree(stdout, SS("and remake the executable. "));
	forwritefree(stdout, SS("          "));
	forwritefree(stdout, SS("            ******* Error ******** "));
	adios(INOUT(3));
	nop();
	
	return ;
}

void pvmfpack()
{
	pvmfinitsend();
	nop();
	
	return ;
}

void pvmfbcast()
{
	pvmfinitsend();
	nop();
	
	return ;
}

void pvmfrecv()
{
	pvmfinitsend();
	nop();
	
	return ;
}

void pvmfunpack()
{
	pvmfinitsend();
	nop();
	
	return ;
}

void pvmfgsize()
{
	pvmfinitsend();
	nop();
	
	return ;
}

void pvmfjoingroup()
{
	pvmfinitsend();
	nop();
	
	return ;
}

void pvmfmytid()
{
	pvmfinitsend();
	nop();
	
	return ;
}

void pvmflvgroup()
{
	pvmfinitsend();
	nop();
	
	return ;
}

void pvmfexit()
{
	pvmfinitsend();
	nop();
	
	return ;
}


