/**********************************************************************/
/* File:                                                              */
/* Author:                                                            */
/* This codes is generated by CFortranTranslator                      */
/* CFortranTranslator is published under GPL license                  */
/* refer to https://github.com/CalvinNeo/CFortranTranslator/ for more */
/**********************************************************************/
#include "../for90std/for90std.h" 
#define USE_FORARRAY 
int main()
{
	forstring a = "          ";
	forstring add = "                    ";
	forstring b = "          ";
	forstring c = "                    ";
	forstring d = "                    ";
	forstring e = "                    ";
	forstring first = "      ";
	int i = 0;
	forstring second = "          ";
	forstring sstring = "                    ";
	/*!声明字符串的方法*/
	/*!Fortran 90 添加*/
	/*!Fortran 77*/
	/*!Fortran 77*/
	/*!Fortran 77*/
	
	/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/
	
	
	a = SS("Hello");
	/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/
	/*!字符串赋值*/
	/*!Fortran 90 可用双引号来封装字符串*/
	b = SS("Hello");
	/*!Fortran 77 只能用单引号来封装字符串*/
	c = SS("That's right.");
	/*!用双引号封装字符串时，可以在字符串中任意使用单引号*/
	
	
	
	sstring = SS("Good morning.");
	/*!d='That''s right.' !用单引号封转字符串时，输出单引号时要连续用两个单引号*/
	/*!e="That's ""right""."!用双引号来封装时，输出双引号也要连续使用两个双引号*/
	/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/
	forwritefree(stdout, sstring);
	sstring(INOUT(6)) = SS("evening.");
	/*!重新设置从第6个字符之后的字符串*/
	forwritefree(stdout, sstring);
	assign_forslice(sstring, SS("Go"), {{1, 2}});
	/*!字符串最前面两个字符变为”Go“*/
	assign_forslice(sstring, SS("!"), {{13, 13}});
	/*!字符串的第13个字符变为“！”*/
	first = SS("Happy ");
	second = SS("Birthday");
	add = first + second;
	/*!经过两个连续的除号可以连接两个字符串*/
	forwritefree(stdout, add);
	
	
	
	
	
	
	
	
	
	
	return 0;
}
