/**********************************************************************/
/* File:                                                              */
/* Author:                                                            */
/* This codes is generated by CFortranTranslator                      */
/* CFortranTranslator is published under GPL license                  */
/* refer to https://github.com/CalvinNeo/CFortranTranslator/ for more */
/**********************************************************************/
#include "../../for90std/for90std.h" 
#define USE_FORARRAY 
int main()
{
	string buf = "                    ";
	int i = 0;
	int j = 0;
	string str = "                    ";
	str = SS("111 222 apple");
	forreadfree(str, &i);
	forwritefree(stdout, i);
	forreadfree(str, &j);
	forwritefree(stdout, j);
	forreadfree(str, &i, &j, &buf);
	forwritefree(stdout, i, j, buf);
	
	
	
	return 0;
}
