/**********************************************************************/
/* File:                                                              */
/* Author:                                                            */
/* This codes is generated by CFortranTranslator                      */
/* CFortranTranslator is published under GPL license                  */
/* refer to https://github.com/CalvinNeo/CFortranTranslator/ for more */
/**********************************************************************/
#include "../for90std/for90std.h"
#define USE_FORARRAY
int main()
{
        const farray<int> a {{1, 1}, {3, 4},make_init_list({1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12})};
        const farray<int> b {{1, 1}, {3, 4},forconcat({make_init_list({1, 2, 3}), make_init_list({4, 5, 6}), make_init_list({7, 8, 9}), make_init_list({10, 11, 12})})};
        const farray<int> c {{1, 1}, {3, 4},forreshape({1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}, {3, 4})};
        forwritefree(stdout, a(INOUT(2), INOUT(3)), b(INOUT(2), INOUT(3)), c(INOUT(2), INOUT(3)));
        //forwritefree(stdout,a(INOUT(2),INOUT(3)));
        return 0;
}
