/**********************************************************************/
/* File:                                                              */
/* Author:                                                            */
/* This codes is generated by CFortranTranslator                      */
/* CFortranTranslator is published under GPL license                  */
/* refer to https://github.com/CalvinNeo/CFortranTranslator/ for more */
/**********************************************************************/
#include "../for90std/for90std.h"
#define USE_FORARRAY
int main()
{
        farray<int> a {{1, 1}, {3, 12}};
        int i = 0;
        const int one = 1;
        const int zero = 0;
        for(i = 1; i <= 3; i += 1){
                assign_forslice(a, make_init_list({one, zero, zero, zero, one, zero, zero, zero, one}), {{i}, {1, 9}});
        }
        /*! assign_forslice(a, make_init_list({one,zero,zero, zero,one,zero, zero,zero,one}),{{i},{1:9}});*/
        forwritefree(stdout, a(INOUT(1), INOUT(1)));
        return 0;
}
