/**********************************************************************/
/* File:                                                              */
/* Author:                                                            */
/* This codes is generated by CFortranTranslator                      */
/* CFortranTranslator is published under GPL license                  */
/* refer to https://github.com/CalvinNeo/CFortranTranslator/ for more */
/**********************************************************************/
#include "../for90std/for90std.h" 
#define USE_FORARRAY 
int main()
{
	farray<double> a {{1, 1}, {3, 4}};
	a = make_init_list({1, -2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,});
	const int const_num_shell_node = 4;
	const farray<long double> edgefixedcompval {{1}, {4},make_init_list({-1, 1, 1, 1,})};
	const farray<long double> nodeprntcoord {{1, 1}, {2, const_num_shell_node},forconcat({make_init_list({-1, -1,}), make_init_list({1, -1,}), make_init_list({1, 1,}), make_init_list({-1, 1,})})};
	/*! fixed component value*/
	forwritefree(stdout, a(INOUT(1), INOUT(3)));
	forwritefree(stdout, edgefixedcompval(INOUT(1)));
	forwritefree(stdout, nodeprntcoord(INOUT(1), INOUT(4)));
	
	
	return 0;
}
