/**********************************************************************/
/* File:                                                              */
/* Author:                                                            */
/* This codes is generated by CFortranTranslator                      */
/* CFortranTranslator is published under GPL license                  */
/* refer to https://github.com/CalvinNeo/CFortranTranslator/ for more */
/**********************************************************************/
#include "../for90std/for90std.h" 
#define USE_FORARRAY 
#include "subr.h"
int main()
{
	double x = 0.0;
	double y = 0.0;
	x = 5.0;
	y = 100.0;
	subr(INOUT(x), INOUT(y), INOUT(10));
	forprintfree(x, y);
	
	
	return 0;
}
